name: Hola Mundo en Java

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      # Compilar el archivo Java
      - name: Compile Java
        run: javac HolaMundo.java

      # Ejecutar el programa Java
      - name: Run Java program
        run: java HolaMundo