name: Workflow con variables
run-name: Ejemplo usando una variable configurada en GitHub Actions

on: workflow_dispatch
env:
  DIA_DE_SEMANA: Lunes
jobs:
  saludo-variables:
    runs-on: ubuntu-latest
    env:
      SALUDO: Hola

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Saludar usando variables locales y globales
        run: echo "$SALUDO, $NOMBRE. Hoy es $DIA_DE_SEMANA!"
        env:
          NOMBRE: Juan

      - name: Saludar usando una variable configurada en GitHub Actions
        run: echo "$SALUDO, ${{ vars.NOMBRE }}. Hoy es $DIA_DE_SEMANA!"
